name = "cf-worker-ws-dev-0415" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
# UUID = "3f38277f-26f8-40f8-b6e6-94c09173ce37"
